greeting:
  message: "hello"

authorization:
  permit-patterns: "/*"

quarkus:
  jackson:
    # 时区配置
    timezone: Asia/Shanghai
  http:
    # 端口号
    port: 10000
    host: 0.0.0.0
  mybatis:
    xmlconfig:
      enable: true
      path: mybatis/config/mybatis-config.xml
  redis:
    hosts: redis://222.128.15.23:9736/14
    password: Ts6jqrQhH9jprCG0kc9e
  # 数据源配置
  datasource:
    # 数据库类型
    db-kind: mysql
    # 用户名
    username: root
    # 密码
    password: s#3dK9$@f2D
    jdbc:
      # 数据库连接地址
      url: jdbc:mysql://222.128.15.23:6033/newsmartcloud?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&useAffectedRows=true
      # 驱动
      driver: com.mysql.cj.jdbc.Driver
      # 连接池配置
      min-size: 1
      max-size: 10
  # 日志配置
  console:
    # 颜色
    color: true
  log:
    console:
      # JSON 格式日志
      json: false
      enable: true
    # 日志级别
    level: INFO
